apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: docker-etcd
    image: lukaszbielinski/docker-etcd:latest

    env:
    - name: ETCD_DATA_DIR
      value: '/var/lib/etcd2'
    - name: ETCD_ADVERTISE_CLIENT_URLS
      value: 'http://192.168.1.145:2379'
    - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
      value: 'http://192.168.1.145:2380'
    - name: ETCD_INITIAL_CLUSTER
      value: 'infra0=http://192.168.1.145:2380,infra1=http://192.168.1.146:2380,infra2=http://192.168.1.147:2380'
    - name: ETCD_INITIAL_CLUSTER_STATE
      value: 'new'
    - name: ETCD_INITIAL_CLUSTER_TOKEN
      value: 'etcd-cluster-1'
    - name: ETCD_LISTEN_CLIENT_URLS
      value: 'http://192.168.1.145:2379,http://127.0.0.1:2379'
    - name: ETCD_LISTEN_PEER_URLS
      value: 'http://192.168.1.145:2380'
    - name: ETCD_NAME
      value: 'infra0'

    volumeMounts:
    - mountPath: /var/lib/etcd2
      name: etcd-data

  volumes:
  - hostPath:
      path: /var/lib/etcd2
    name: etcd-data
